### ISSUE TITLE
Tag with letter with accent is invalid

### ISSUE THREAD

**Issue by amesure** [colorhook/jsxml#12]
Hello,
When I try to parse this xml, I have an 'the start tag is invalid' error:

``<DataFeed xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><Row TrancheHoraire="0:0" EPEnvoyésCumulés="1"/></DataFeed>``

When I remove the 'é', I have no error:

<DataFeed xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><Row TrancheHoraire="0:0" EPEnvoyesCumules="1"/></DataFeed>

Could you change the regexp startTag to include the letters with accent please?

Thank you so much,
Anne-Laure

**Comment by colorhook** [comment]
You can use the latest version in your project now. Thank you for submitting this bug.

**Comment by amesure** [comment]
Thx for the fix. :)
