### ISSUE TITLE
Remove function is not removing index of attribute

### ISSUE THREAD

**Issue by bhishp** [colorhook/jsxml#8]
remove: function() {
      if (!this._parent) {
        return;
      }
      var nk = this._nodeKind;
      var list;
      if (nk === NodeKind.ATTRIBUTE) {
        list = this._parent._attributes;
      } else {
        list = this._parent._children;
      }
      var index = list.indexOf(this);
      if (index !== -1) {
        list.splice(i, 1)
      }
    }

Function is calling `list.splice(i,1)`, rather than `list.splice(index,1)` - causing the incorrect attribute to be removed in some cases.

Fix in PR #9

**Comment by colorhook** [comment]
The code was merged and v0.8.0 published, thanks very much!
